### ISSUE TITLE
Just running default command not working unless I select the Terminal menu bar

### ISSUE THREAD

**Issue by boguwei** [mklement0/ttab#10] opened 2017-05-12 16:56 UTC
When I just run `ttab`, the frontmost terminal window doesn't open a new tab until I select the Terminal menu bar with my mouse.

(FWIW, when running `ttab -w`, a new Terminal window opens just fine). Not familiar with apple script, but using the macOS script editor to manually run the generated apple script (from `--dry-run`) has the same results as above. 

I have enabled Accessibility for Terminal.app in Security & Privacy settings, and I'm on macOS 10.12.4.

Any help debugging would be appreciated. Absolutely loved this utility when it was working to help manage tabs and windows in scripts.

**Comment by mklement0** [comment] 2017-05-12 18:42
It does sound like the problem is related to the Accessibility feature - GUI scripting (simulating menu selections) is required to open a new tab, because there's no AppleScript support for that.

Unfortunately, I cannot reproduce your symptom (I'm running macOS 10.12.4 too).

* When did it start?

* Does `Console.app` show anything of interest?

* Have you tried recreating the entry for `Terminal.app` in System Preferences > Security & Privacy > Privacy > Accessibility?

* Have you tried `tccutil reset Accessibility`? Caveat: This will wipe out existing authorizations.

P.S.: Thanks for the nice feedback.

**Comment by boguwei** [comment] 2017-05-12 20:01
`tccutil reset Accessibility` seems to have done the trick! Hopefully this will stick. I'll comment back here if the behavior reverts (which would be unfortunate, since a hard reset is too painful to do very often if you have to add back all authorizations after.

It's really weird. I restarted my MBP (without having done the above yet) and `ttab` worked correctly once, and then reverted to the behavior I mentioned. It stopped working about a month ago? I can't really recall it being timed with anything else I've done. 

I find it really odd that clicking on the macOS menu bar opens the tab and completes the script (from the dry run): 
```
tell application "Terminal"
  
  activate
  repeat until frontmost
      delay 0.1
  end repeat
  tell application "System Events" to tell menu 1 of menu item 2 of menu 1 of menu bar item 3 of menu bar 1 of application process "Terminal" to click (first menu item whose value of attribute "AXMenuItemCmdChar" is "T" and value of attribute "AXMenuItemCmdModifiers" is 0)
  set newTab to selected tab of front window
  
  
  
end tell

return
```

It's almost like it gets stuck in the repeat loop until I click on the menu bar. 

Re: your other suggestions:
* I have tried to delete and recreate the Terminal.app entry - no success. 
* There are a couple of entries that seem to happen consistently in the console when I go through the process. 
    1. when I select a terminal window: `kernel | loginwindow is not entitled`
    2. when I run ttab: `taskgated | MacOS error: -67062`

Anyway, the hard reset seems to have done the trick. Much appreciated!

**Comment by mklement0** [comment] 2017-05-12 20:09
My pleasure, and thanks for the detailed feedback. I'll close the issue, but we can revisit if needed.

**Closed by mklement0** 2017-05-12 20:09 UTC

**Comment by boguwei** [comment] 2017-05-12 20:44
Broke again 😞 . not sure why my accessibility settings are getting messed up. Will update with anything else interesting.

**Comment by mklement0** [comment] 2017-05-12 21:02
Sorry to hear it. When it's broken, does `Terminal.app` _visually_ become frontmost, i.e., do the close / minimize / full-screen buttons in the top-left corner of the title bar turn _colored_?

The fact that you can click on Terminal's menu bar suggests that it _is_ frontmost.

**Comment by boguwei** [comment] 2017-05-12 21:31
Yes. The Terminal is frontmost. Almost always when I run ttab, I'm running it directly from a terminal window anyway, so there shouldn't have been a focus switch.

**Comment by boguwei** [comment] 2017-05-12 21:47
Also: executing a command with ttab (like `ttab 'git status'`) will run the command in the current Terminal window.

**Comment by mklement0** [comment] 2017-05-12 22:07
All very mysterious. 

There's not much to be found with respect to your `Console.app` findings, except possibly this: https://discussions.apple.com/thread/7705551?start=0&tstart=0
