### ISSUE TITLE
Cannot run ttab - SyntaxError: Unexpected token '{'

### ISSUE THREAD

**Issue by n-antimatter** [mklement0/ttab#52] opened 2023-01-09 13:04 UTC
I'm having the issue below. It went from working to not working on a project seemingly after changing my project's branch and reinstalling node_modules but that hasn't changed the package version of ttab or the way it's being used

OSX bash (zsh. Tried both but same issue)
ttab v0.7.2 (tried v0.7.3 but same issue)

```
kTHIS_NAME=${BASH_SOURCE##*/}
            ^

SyntaxError: Unexpected token '{'
```

<img width="752" alt="Screenshot 2023-01-09 at 12 10 24" src="https://user-images.githubusercontent.com/121939681/211313735-b39cdb72-8215-4356-84d9-9c327747a37e.png">

**Comment by mklement0** [comment] 2023-01-09 13:46
Your symptom suggests that `ttab` is unexpectedly being executed by `node` rather than `bash`.
Note that `ttab` is a shell script with a `#!/usr/bin/env bash` shebang line.

**Comment by mklement0** [comment] 2023-01-09 17:28
If it runs as a _shell command_, it works fine - I assume it still works for you _interactively_, correct?

I strongly suspect that the problem is specific to your project - nothing has changed recently, and I see no reason for `node` to try interpret the script - unless the shebang line was somehow modified.

If you inspect the `ttab` shell script you're running, does it still start with `#!/usr/bin/env bash`?

**Comment by mklement0** [comment] 2023-01-09 21:12
Thanks for confirming.

That implies that there's a problem with how `ttab` is being invoked in your project, and not a problem with `ttab` itself, and I can only see two ways that that would happen:

Taking a closer look at the error message, the implication is that you're running the following, which obviously won't work:
 `node ./node_modules/.bin/ttab`

**Comment by mklement0** [comment] 2023-01-10 02:43
@n-antimatter, I'm closing this for now, in the absence of evidence of a problem with `ttab` itself.

We can revisit if you do find such evidence and/or discover a pitfall with respect to `ttab`'s  use in Node.js projects that should be documented.

**Closed by mklement0** 2023-01-10 02:43 UTC
Labels: resolution-external

**Comment by mklement0** [comment] 2023-01-10 15:30
My pleasure, @n-antimatter. Curious that `yarn` behaves differently (I'm not familiar with it).

**Comment by evisong** [comment] 2023-12-14 03:28
I guess this is related to a breaking change in yarn 2+ (yarn 1.x works fine) tracked in yarnpkg/berry#882.

According to https://github.com/yarnpkg/berry/issues/882#issuecomment-1599478009 :
> `bin` entries should be able to point to non-JS shebang scripts; this is still not possible at the moment.
Yarn won't support this use case in latest versions (i.e. yarn@4).

A workaround `$(yarn bin ttab)` works well on my Mac.

FYI, I even run yarn 4 workspaces command for my mono-repo like this:

```bash
TTAB=$(yarn bin ttab) yarn workspaces foreach -A exec '$TTAB -G exec yarn start'
```
